#!/bin/sh

# 拼接所有的参数做变量
all=""
for var in "$@"
do
    # echo "$var"
    if [[ "${all}" = "" ]]
    then
        all="\"${var}\""
    else
        all="${all} \"${var}\""
    fi
done

# echo "${all}"
alias go="/Applications/5.app/Contents/MacOS/Emacs ${all} -nw"
go
